"""CIK <-> symbol point-in-time interval map (spec: M4 fundamentals overlay).

cik_map.csv is a COMMITTED artifact (symbol,cik,start,end; start inclusive,
end exclusive, empty end = current) generated by scripts/build_cik_map.py --
treat as frozen data, regenerate deliberately and review the diff (sources +
validation: src/trading/venues/universes/sources/PROVENANCE.md).

A fundamentals row attaches to the symbol whose interval contains the row's
FILED date: a renamed company's pre-rename filings land on the old symbol
(FB) and post-rename filings on the new one (META) while both share one
CIK's TTM continuity. Membership symbols with NO row here (mostly acquired/
delisted companies EDGAR no longer lists a ticker for) simply get no
fundamentals and rank neutral (0.5) -- fail-open by design.
"""

from __future__ import annotations

import datetime
from pathlib import Path

import pandas as pd

DEFAULT_CIK_MAP_CSV = Path(__file__).parent / "cik_map.csv"


def load_cik_map(path: Path | None = None) -> pd.DataFrame:
    df = pd.read_csv(path or DEFAULT_CIK_MAP_CSV, comment="#", dtype=str).fillna("")
    df["cik"] = df["cik"].astype(int)
    return df


def cik_for(cik_map: pd.DataFrame, symbol: str, as_of: datetime.date) -> int | None:
    iso = as_of.isoformat()
    rows = cik_map[
        (cik_map["symbol"] == symbol)
        & (cik_map["start"] <= iso)
        & ((cik_map["end"] == "") | (iso < cik_map["end"]))
    ]
    return int(rows.iloc[0]["cik"]) if len(rows) else None


def interval_slice(frame: pd.DataFrame, start: str, end: str) -> pd.DataFrame:
    """Rows of a filed-indexed frame whose FILED date falls in [start, end)."""
    out = frame[frame.index >= pd.Timestamp(start, tz="UTC")]
    if end:
        out = out[out.index < pd.Timestamp(end, tz="UTC")]
    return out
